-- =====================================================
-- User Management Setup: User Roles Table
-- =====================================================
-- This migration creates the user_roles table for assigning
-- application roles to users for RBAC

-- Create user_roles table
CREATE TABLE user_roles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  role app_role NOT NULL,
  
  -- Ensure unique user-role combinations
  UNIQUE(user_id, role)
);

-- Enable Row Level Security
ALTER TABLE user_roles ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
-- Users can view their own roles
CREATE POLICY "Users can view own roles" ON user_roles
  FOR SELECT USING (auth.uid() = user_id);

-- Only users with user_roles.view permission can view all roles
CREATE POLICY "Authorized users can view all roles" ON user_roles
  FOR SELECT USING (has_permission('user_roles.view'));

-- Only users with user_roles.update permission can modify roles
CREATE POLICY "Authorized users can update roles" ON user_roles
  FOR ALL USING (has_permission('user_roles.update'));

-- Add table comment
COMMENT ON TABLE user_roles IS 'Application roles for each user.';
