-- =====================================================
-- User Management Setup: Role Permissions Table
-- =====================================================
-- This migration creates the role_permissions table that defines
-- which permissions each role has access to

-- Create role_permissions table
CREATE TABLE role_permissions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role app_role NOT NULL,
  permission app_permission NOT NULL,
  
  -- Ensure unique role-permission combinations
  UNIQUE(role, permission)
);

-- Enable Row Level Security
ALTER TABLE role_permissions ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
-- All authenticated users can view role permissions (needed for has_permission function)
CREATE POLICY "Authenticated users can view role permissions" ON role_permissions
  FOR SELECT TO authenticated USING (true);

-- Only superadmins can modify role permissions
CREATE POLICY "Superadmins can manage role permissions" ON role_permissions
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM user_roles 
      WHERE user_id = auth.uid() 
      AND role = 'superadmin'
    )
  );

-- Add table comment
COMMENT ON TABLE role_permissions IS 'Application permissions for each role.';
